export const SET_HE_THONG_RAP_CHIEU = 'SET_HE_THONG_RAP_CHIEU';
export const SET_CHI_TIET_PHIM = 'SET_CHI_TIET_PHIM';
export const SET_CUM_RAP_THEO_HE_THONG = 'SET_CUM_RAP_THEO_HE_THONG';
export const SET_LICH_CHIEU_PHIM = 'SET_LICH_CHIEU_PHIM';
export const SET_THONG_TIN_HE_THONG_RAP='SET_THONG_TIN_HE_THONG_RAP';